// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: openai-proxy.proto

package openaipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A chunk of raw audio data (e.g., bytes from the browser MediaRecorder)
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_openai_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_openai_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_openai_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Final transcript after all audio is received
type Transcript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_openai_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_openai_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_openai_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *Transcript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A message from the user in a chat session
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_openai_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_openai_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_openai_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// A streamed partial or final response from the AI
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_openai_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openai_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_openai_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_openai_proxy_proto protoreflect.FileDescriptor

const file_openai_proxy_proto_rawDesc = "" +
	"\n" +
	"\x12openai-proxy.proto\x12\vopenaiproxy\" \n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\" \n" +
	"\n" +
	"Transcript\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\":\n" +
	"\vChatMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\"\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\x90\x01\n" +
	"\vOpenAIProxy\x12@\n" +
	"\n" +
	"Transcribe\x12\x17.openaiproxy.AudioChunk\x1a\x17.openaiproxy.Transcript(\x01\x12?\n" +
	"\x04Chat\x12\x18.openaiproxy.ChatMessage\x1a\x19.openaiproxy.ChatResponse(\x010\x01BEZCgithub.com/izstoev10/my-ai_assistant/services/openai-proxy;openaipbb\x06proto3"

var (
	file_openai_proxy_proto_rawDescOnce sync.Once
	file_openai_proxy_proto_rawDescData []byte
)

func file_openai_proxy_proto_rawDescGZIP() []byte {
	file_openai_proxy_proto_rawDescOnce.Do(func() {
		file_openai_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openai_proxy_proto_rawDesc), len(file_openai_proxy_proto_rawDesc)))
	})
	return file_openai_proxy_proto_rawDescData
}

var file_openai_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openai_proxy_proto_goTypes = []any{
	(*AudioChunk)(nil),   // 0: openaiproxy.AudioChunk
	(*Transcript)(nil),   // 1: openaiproxy.Transcript
	(*ChatMessage)(nil),  // 2: openaiproxy.ChatMessage
	(*ChatResponse)(nil), // 3: openaiproxy.ChatResponse
}
var file_openai_proxy_proto_depIdxs = []int32{
	0, // 0: openaiproxy.OpenAIProxy.Transcribe:input_type -> openaiproxy.AudioChunk
	2, // 1: openaiproxy.OpenAIProxy.Chat:input_type -> openaiproxy.ChatMessage
	1, // 2: openaiproxy.OpenAIProxy.Transcribe:output_type -> openaiproxy.Transcript
	3, // 3: openaiproxy.OpenAIProxy.Chat:output_type -> openaiproxy.ChatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openai_proxy_proto_init() }
func file_openai_proxy_proto_init() {
	if File_openai_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openai_proxy_proto_rawDesc), len(file_openai_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openai_proxy_proto_goTypes,
		DependencyIndexes: file_openai_proxy_proto_depIdxs,
		MessageInfos:      file_openai_proxy_proto_msgTypes,
	}.Build()
	File_openai_proxy_proto = out.File
	file_openai_proxy_proto_goTypes = nil
	file_openai_proxy_proto_depIdxs = nil
}
